name: hundredpay
description: A new Flutter plugin project.
version: 0.0.2
homepage: https://github.com/shop100global/100pay-flutter-sdk
repository: https://github.com/shop100global/100pay-flutter-sdk
issue_tracker: https://github.com/shop100global/100pay-flutter-sdk/issues
# dependencies: 

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  plugin_platform_interface: ^2.0.2
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  plugin:
    platforms:
      android:
        package: kn.hundredpay.hundredpay
        pluginClass: HundredpayPlugin
      ios:
        pluginClass: HundredpayPlugin
      linux:
        pluginClass: HundredpayPlugin
      macos:
        pluginClass: HundredpayPlugin
      windows:
        pluginClass: HundredpayPluginCApi


